<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Lav-Gupta.domain.name" failures="0" tests="2" name="Default test(failed)" time="47.761" errors="0" timestamp="30 Jul 2020 08:32:24 GMT">
  <testcase classname="com.qa.testcases.AppiumDemo" name="@BeforeClass setUp" time="47.732">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.qa.base.TestBase.initialization(TestBase.java:90)
	at com.qa.testcases.AppiumDemo.setUp(AppiumDemo.java:23)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeClass setUp -->
  <testcase classname="com.qa.testcases.AppiumDemo" name="@AfterClass tearDown" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterClass tearDown -->
  <testcase classname="com.qa.testcases.AppiumDemo" name="loginIntoApplicationViaEmail" time="0.0">
    <skipped/>
  </testcase> <!-- loginIntoApplicationViaEmail -->
  <testcase classname="com.qa.testcases.AppiumDemo" name="VerifyDesiredProductDetailsOnCheckoutPage" time="0.0">
    <skipped/>
  </testcase> <!-- VerifyDesiredProductDetailsOnCheckoutPage -->
</testsuite> <!-- Default test(failed) -->
